### ISSUE TITLE
Background colour in OBApps

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen1-dark-theme#4]
This is the only issue I've found so far on my system. 
It is fine in Crunchy-dark-grey (bottom scrot)
![screenshot](http://i.imgbox.com/9RW2RJ3n.jpg)

**Comment by 2ion** [comment]
…because I can't handle this.

**Comment by capn-damo** [comment]
Now it's working fine! Some weirdness with theme switches on my system?

**Comment by hhhorb** [comment]
I've encountered weirdness before as well. GTK3 weirdness, xfce4-notifyd weirdness, etc... I'm not sure if it's because their all based off of Greybird, but I've seen settings from one carry over to the next. Always best to logout/login after theme changes if you're bugshooting.
